services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=go-splearn'
      - 'MYSQL_USER=gopher'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data: